version: '3.2'
services:
  app:
    image: hello-app
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - cinet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306
    networks:
      - cinet
networks:
  cinet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
